(function () {
  'use strict';

  function L(id, question, options, correct, actions, result, evidence, explanation, boundary, transfer) {
    return {id, question, options, correct, actions, result, evidence, explanation, boundary, transfer};
  }

  const lessons = {
    'X3-01':L('X3-01','升高温度后，分子热运动的统计表现怎样？',[['faster','平均动能增大、运动更剧烈'],['same','所有分子速率不变'],['aligned','分子改作同向运动']],'faster',[{selector:'#temp',value:'520'}],'分子运动更剧烈，但瞬时速度仍有快有慢。','温度、碰撞频率和运动轨迹由同一状态联动。','温度反映大量分子热运动的统计特征。','模型粒子不代表真实大小，画面速度也不是标定值。','微观解释题要从大量粒子的统计规律作答。'),
    'X3-02':L('X3-02','同种物质的质量加倍，物质的量怎样变化？',[['double','加倍'],['same','不变'],['half','减半']],'double',[{selector:'#mass',value:'36'}],'在摩尔质量不变时，n=m/M 随质量成正比。','天平读数、物质的量和粒子数同步变化。','一摩尔所含微粒数由阿伏加德罗常数联系。','画面只能抽样显示微粒，不能逐个画出真实数量。','先辨认质量、摩尔质量和物质的量，再使用 n=m/M。'),
    'X3-03':L('X3-03','显微镜下的布朗颗粒为什么走折线？',[['collisions','受到液体分子不平衡碰撞'],['alive','颗粒有生命'],['flow','液体整体定向流动']],'collisions',[{selector:'#temp',value:'520'}],'升温后无规则碰撞更剧烈，颗粒轨迹更曲折。','分子运动、碰撞和颗粒轨迹同时增强。','布朗运动间接证明分子的无规则热运动。','单条轨迹有随机波动，应比较统计趋势。','实验解释要区分被观察颗粒与不可见分子。'),
    'X3-04':L('X3-04','两分子从很远处逐渐靠近，分子力如何变化？',[['switch','先以引力为主，过近后斥力迅速增强'],['only','始终只有引力'],['zero','任意距离都为零']],'switch',[{selector:'#dist',value:'0.75'}],'过近时斥力占主导，存在合力为零的平衡距离。','势能曲线、合力方向和分子间距共同变化。','分子力是引力与斥力综合作用的结果。','曲线是定性模型，不给出具体物质的标定参数。','看到分子间距变化，要分远、平衡和过近三段。'),
    'X3-05':L('X3-05','一定量物质温度升高时，分子平均动能怎样？',[['up','增大'],['same','不变'],['zero','归零']],'up',[{selector:'#temp',value:'650'}],'温度升高使分子平均动能增大，内能还可能含势能变化。','温度、动能仪表和内能组成同步更新。','内能是大量分子热运动动能和相互作用势能的总和。','理想气体常忽略分子势能，真实物态转换不能忽略。','判断内能变化先看温度、物态和物质的量。'),
    'X3-06':L('X3-06','两物体温度相同意味着什么？',[['equilibrium','接触后无宏观净热传递'],['energy','内能一定相等'],['molecules','每个分子速率相等']],'equilibrium',[{selector:'#tempA',value:'420'},{selector:'#tempB',value:'420'}],'温度相同对应热平衡条件，不保证内能相等。','两个温度计读数重合，净热流提示归零。','热平衡状态用共同温度描述。','物质的量和种类不同，内能仍可不同。','“等温”不能直接替换为“等内能”。'),
    'X3-07':L('X3-07','密闭气体体积减小时，若 T、n 不变，压强怎样？',[['up','增大'],['same','不变'],['down','减小']],'up',[{selector:'#vol',value:'1.2'}],'体积减小，单位时间撞壁更频繁，压强增大。','活塞位置、分子密度、碰撞和 pV=nRT 读数一致。','一定量理想气体定温时 p 与 V 成反比。','理想气体模型忽略分子自身大小和分子力。','状态参量题先确认哪些量不变。'),
    'X3-08':L('X3-08','玻意耳定律实验中应保持哪个量不变？',[['temp','温度和气体物质的量'],['pressure','压强'],['volume','体积']],'temp',[{selector:'#vol',value:'1.4'}],'等温压缩时 p 增大，pV 保持近似不变。','p-V 曲线、活塞和乘积读数互相核对。','一定质量理想气体在温度不变时 pV=常量。','快速压缩可能来不及与环境换热，不再近似等温。','实验条件要和所用气体定律一一对应。'),
    'X3-09':L('X3-09','压强不变时升高绝对温度，气体体积怎样？',[['up','增大'],['same','不变'],['negative','变成负值']],'up',[{selector:'#temp',value:'560'}],'定压条件下 V/T 保持近似不变。','活塞、温标和 V-T 图线共同右移。','查理定律中的温度必须使用开尔文温标。','外推到绝对零度不是把真实气体无限延伸。','比例式温度必须先换算为热力学温度。'),
    'X3-10':L('X3-10','同一容器内增加气体物质的量，T、V 不变时 p 怎样？',[['up','增大'],['same','不变'],['down','减小']],'up',[{selector:'#amount',value:'2.0'}],'分子数增加使撞壁频率增加，压强增大。','粒子数、物质的量和状态方程读数同步。','理想气体满足 pV=nRT。','模型只展示比例关系，不代表具体气体标定。','综合状态题先把每个状态量和微观含义对应。'),
    'X3-11':L('X3-11','p-V 图中气体膨胀时，对外做功如何读出？',[['area','过程曲线下的面积'],['slope','曲线斜率'],['point','终点压强']],'area',[{selector:'#v2',value:'4.5'}],'对外做功等于过程曲线下的有向面积。','起终态、过程曲线、阴影面积和功读数一致。','准静态过程有 W外=∫p dV。','只凭两个端点不能确定任意过程的功。','p-V 图先看方向，再用面积判断功的正负和大小。'),
    'X3-12':L('X3-12','一定量理想气体从状态 1 到 2，哪个量由端点唯一决定？',[['state','内能变化'],['heat','吸收热量'],['work','过程功']],'state',[{selector:'#v',value:'4.0'},{selector:'#t',value:'520'}],'理想气体内能变化由温度端点决定，热量和功依赖过程。','状态点和 pV/T 的约束同步改变。','状态函数只由始末状态决定。','实际气体内能还可能受分子势能影响。','先区分状态量与过程量。'),
    'X3-13':L('X3-13','气体沿给定 p-V 路径膨胀时，外界对气体做功 W 的符号怎样？',[['negative','W<0'],['positive','W>0'],['zero','必为零']],'negative',[{selector:'#volume',value:'4.2'}],'膨胀时外界对气体做负功，且与 p-V 面积严格对应。','同一条路径同时生成活塞运动、面积、W 和 ΔU=Q+W。','本页采用外界对气体做功为正的符号约定。','直线路径是受控准静态示意，非任意快速过程。','先写符号约定，再核对 Q、W、ΔU 的能量账。'),
    'X3-14':L('X3-14','热机效率能否达到 100%？',[['no','不能'],['yes','只要提高高温热源就一定能'],['cold','低温热源吸热为零即可']],'no',[{selector:'#hot',value:'760'},{selector:'#cold',value:'300'}],'即使理想可逆热机也必须向低温热源放热。','热流方向、卡诺上限和设定效率同时显示。','第二定律限制热功转换方向和效率上限。','实际热机还受摩擦、传热温差等不可逆因素限制。','效率题先检查是否超过卡诺上限。'),
    'X3-15':L('X3-15','能量守恒是否意味着所有能量都同样易于利用？',[['no','不意味着；能量品质会退化'],['yes','任何内能都能完全变成功'],['lost','能量会凭空消失']],'no',[{selector:'#internal',value:'70'}],'总能量守恒，但向分散内能转化后可利用程度降低。','输入、有效输出、内能增加和能量账平衡。','守恒定律管总量，第二定律管过程方向和品质。','“耗散”不是能量消失。','能量分析同时写数量守恒与品质变化。'),
    'X3-16':L('X3-16','热量会自发地从低温物体传向高温物体吗？',[['no','不会'],['yes','总会'],['equal','只在等温时持续']],'no',[{selector:'#hot',value:'650'},{selector:'#cold',value:'260'}],'自发传热方向是从高温到低温。','温差、热流箭头和不可逆提示一致。','克劳修斯表述给出热传导的方向性。','制冷机可逆向搬运热量，但必须有外界做功。','判断自发过程时不要忽略外界功。'),
    'X3-17':L('X3-17','晶体和非晶体最关键的结构区别是什么？',[['order','长程有序程度不同'],['material','是否一定由不同元素组成'],['temp','室温一定不同']],'order',[{selector:'#crystalBtn'}],'晶体具有更明确的长程有序，非晶体缺少长程周期性。','微观排列、衍射图样和宏观性质联动。','结构有序性决定各向异性和熔化特征等差异。','多晶体宏观上可近似各向同性。','材料判断要把微观结构和宏观证据相互对应。'),
    'X3-18':L('X3-18','两侧接触线对细针的竖直支持力怎样合成？',[['components','2σLsinα'],['single','只有 σL'],['weight','必定等于任意重力']],'components',[{selector:'#angle',value:'55'}],'两条对称接触线的竖直分量相加，水平分量抵消。','切向力箭头、接触角和 Fy=2σLsinα 使用同一几何。','表面张力沿液面切线且垂直接触线。','本页忽略浮力；L 是单侧接触线长度。','受力题先画每一条接触线的力，再分解合成。'),
    'X3-19':L('X3-19','光频率低于截止频率时，只增大光强会有光电子吗？',[['no','不会'],['yes','会增加到逸出'],['delay','等足够久就会']],'no',[{selector:'#nu',value:'4.0'},{selector:'#int',value:'9'}],'频率不足时单个光子能量不够，增大光强仍无光电子。','频率、逸出功、最大初动能和电流读数共同给证据。','光电效应满足 Ek,max=hν-W0。','模型不描述具体材料表面态和实验误差。','先比较 ν 与截止频率，再讨论光强影响电流。'),
    'X3-20':L('X3-20','双缝实验中单个粒子的落点能否按固定顺序预言？',[['random','不能；只可预言概率分布'],['fixed','能逐点确定'],['wave','粒子会分裂成两半']],'random',[{selector:'#mom',value:'3.8'}],'单次落点随机，许多落点按双缝概率分布累积成条纹。','页面用概率分布拒绝抽样生成落点，而非按编号画正弦。','波函数给出概率幅，测量结果具有统计性。','有限样本条纹会有涨落，不能要求每次完全相同。','区分单次事件与大量事件的统计规律。'),
    'X3-21':L('X3-21','卢瑟福散射中少数 α 粒子大角偏转说明什么？',[['nucleus','正电荷和大部分质量集中在很小的原子核'],['uniform','正电荷均匀铺满原子'],['electrons','电子质量占主要部分']],'nucleus',[{selector:'#b',value:'8'}],'近心入射时库仑斥力更强，偏转角更大。','瞄准参数、轨迹和核式结构示意共同变化。','大角散射支持原子的核式结构。','经典轨迹是示意，不含量子散射截面。','由实验现象反推模型时要抓住少数大角事件。'),
    'X3-22':L('X3-22','电子从高能级跃迁到低能级时发生什么？',[['emit','发射能量等于能级差的光子'],['absorb','必须吸收光子'],['continuous','发出任意连续能量']],'emit',[{selector:'#ni',value:'4'},{selector:'#nf',value:'2'}],'向下跃迁发射光子，hν=Ei-Ef。','能级差、跃迁箭头、频率和谱线同步。','原子能级分立导致发射光谱离散。','玻尔模型适合氢样原子的基础解释。','能级跃迁题先判方向，再取能量差的正值。'),
    'X3-23':L('X3-23','不同元素的线状光谱为何可作“指纹”？',[['levels','各元素能级结构不同'],['temperature','只由温度决定'],['continuous','所有元素谱线连续相同']],'levels',[{selector:'#element',value:'2'}],'切换元素后谱线位置随能级差改变。','元素选择、跃迁和谱线位置一一对应。','线状光谱反映原子分立能级。','实际谱线还会受精细结构、展宽和环境影响。','光谱识别要比较谱线位置组合，不只看一种颜色。'),
    'X3-24':L('X3-24','原子核的质量数 A 等于什么？',[['sum','质子数 Z 与中子数 N 之和'],['charge','只等于质子数'],['electrons','等于电子数']],'sum',[{selector:'#z',value:'8'},{selector:'#n',value:'8'}],'A=Z+N；元素种类由 Z 决定。','核子计数、核素符号和电荷状态分别显示。','同位素有相同 Z、不同 N。','核质量不等于自由核子质量简单相加，存在质量亏损。','核素符号题逐项核对 A、Z、N。'),
    'X3-25':L('X3-25','β− 衰变前后质量数 A 和电荷数 Z 如何变化？',[['rule','A 不变，Z 增加 1'],['both','A、Z 都减 1'],['same','A、Z 都不变']],'rule',[{selector:'#type',value:'1'}],'β− 衰变把一个中子转化为质子，A 不变、Z+1。','核内计数、衰变粒子和守恒账同步。','核反应方程必须守恒质量数与电荷数。','完整弱衰变还包含反中微子。','写核方程先守恒 A、Z，再辨粒子。'),
    'X3-26':L('X3-26','经过两个半衰期后，未衰变核数平均剩多少？',[['quarter','初始的 1/4'],['half','初始的 1/2'],['zero','全部衰变']],'quarter',[{selector:'#half',value:'10'},{selector:'#time',value:'20'}],'两个半衰期后剩余比例为 (1/2)²=1/4。','核数抽样、指数曲线和 N=N0(1/2)^(t/T) 一致。','半衰期描述大量原子核的统计规律。','不能据此预言某个原子核的确切衰变时刻。','先算经历了几个半衰期，再求剩余比例。'),
    'X3-27':L('X3-27','补全核反应方程最先检查哪两个守恒量？',[['az','质量数 A 和电荷数 Z'],['mass','宏观质量数值完全不变'],['energy','只检查动能']],'az',[{selector:'#template',value:'2'}],'反应式两侧 A、Z 必须分别守恒。','方程模板、缺失粒子和双重守恒账联动。','核反应还满足能量和动量守恒。','静质量之和可因结合能而改变，不能与 A 守恒混淆。','先列 A、Z 两行守恒，再识别未知粒子。'),
    'X3-28':L('X3-28','质量亏损 Δm 对应的能量由什么关系给出？',[['einstein','E=Δmc²'],['linear','E=Δm/c²'],['none','质量与能量无关']],'einstein',[{selector:'#dm',value:'0.15'}],'质量亏损增大时对应能量按 E=Δmc² 增大。','质量差、能量换算和反应类型读数同步。','核能来自反应前后静质量差。','输入是教学参数，不代表任意核反应的真实 Δm。','核能计算先统一质量单位，再换算能量。'),
    'X3-29':L('X3-29','比较不同核素结合紧密程度应优先看什么？',[['average','平均结合能 Eb/A'],['total','只看总结合能'],['mass','只看质量数 A']],'average',[{selector:'#a',value:'4'},{selector:'#compare',value:'6'}],'平均结合能越大通常表示核子结合越紧。','页面只在有限真实核素表内比较 Eb、Eb/A 和质量亏损。','总结合能随核子数增多，跨核素应比较每核子平均值。','平均结合能不能单独判定全部衰变通道和半衰期。','比较稳定趋势时写清“结合紧密”与“放射性稳定”的边界。'),
    'X3-30':L('X3-30','链式裂变要持续，关键条件是什么？',[['neutrons','每代有足够中子继续引发裂变'],['heat','只要温度高'],['single','一次裂变即可无限继续']],'neutrons',[{selector:'#neutrons',value:'3'}],'中子繁殖与损失的竞争决定链式反应发展。','代数、中子数、吸收和能量释放记录联动。','临界条件可用有效增殖因子描述。','本页是代际示意，不替代反应堆中子输运计算。','链式反应题要同时看产生、泄漏和吸收。'),
    'X3-31':L('X3-31','提高温度和约束是否足以给出精确聚变概率？',[['no','不能；这里只能判断条件趋势'],['yes','可直接换算百分比'],['certain','条件高就必然聚变']],'no',[{selector:'#temp',value:'9'},{selector:'#confine',value:'9'}],'高温、约束和接近使条件更有利，但页面不输出伪造概率。','能垒、粒子接近和“条件趋势”表盘联动。','真实反应率需要截面、粒子分布、密度与约束时间等。','等级滑块没有实验标定，不能冒充百分概率。','定性模型只能下定性结论。'),
    'X3-32':L('X3-32','某反应满足电荷守恒，能否据此断言通道一定成立？',[['no','不能；电荷守恒只是必要条件'],['yes','可以'],['ignore','电荷不需要守恒']],'no',[{selector:'#particle',value:'2'},{selector:'#reaction',value:'1'}],'电荷相等只说明这一项必要条件满足。','页面明确继续要求能量、动量、角动量等条件。','守恒定律可排除通道，但单一守恒通过不能充分证明通道。','本页不计算真实反应截面和全部量子数。','判断反应通道要逐项核对所有守恒条件。'),
    'X3-33':L('X3-33','温度升高而分子质量不变，速率分布怎样变化？',[['spread','峰位右移、峰值降低、分布变宽'],['rigid','整条曲线只竖直上移'],['same','完全不变']],'spread',[{selector:'#temp',value:'650'}],'高温下高速分子比例增加，分布变宽且面积仍归一。','分子箭头、直方图、分布曲线和数值积分一致。','麦克斯韦速率分布描述大量分子的统计分布。','经典分布适用于稀薄、非相对论理想气体。','分布图要同时看峰位、峰高、宽度和面积。'),
    'X3-34':L('X3-34','布朗运动的均方位移曲线应怎样得到？',[['ensemble','由许多随机轨迹的位移平方取平均'],['preset','预先画一条平滑曲线'],['single','只取一条轨迹终点']],'ensemble',[{selector:'#temp',value:'390'}],'页面用 72 个随机行走样本实时计算 MSD。','样本轨迹、实测 MSD 和历史曲线来自同一系综。','扩散过程的均方位移是统计量。','有限样本会涨落，模型步长不等于真实长度和时间。','实验数据要说明样本数和统计方法。'),
    'X3-35':L('X3-35','液晶、半导体、纳米材料的性质主要由什么决定？',[['structure','结构、尺度及外场/温度条件'],['name','只由材料名称'],['color','只由肉眼颜色']],'structure',[{selector:'#nano'},{selector:'#size',value:'20'}],'纳米尺度改变表面占比和量子尺寸等效应，材料性质随结构条件变化。','材料类型、微结构、尺度和性质提示联动。','宏观性能来自微观结构及其可控响应。','本页为类别比较，具体器件需要材料参数。','新材料题要把结构—性质—应用连成证据链。'),
    'X3-36':L('X3-36','接触角恰为 90° 时，理想毛细高度怎样？',[['zero','h=0，是升降临界'],['rise','一定上升'],['fall','一定下降']],'zero',[{selector:'#theta',value:'90'}],'cos90°=0，理想模型中液柱不升不降。','接触角、cosθ、高度和临界状态同时归零。','h=2σcosθ/(ρgr) 的正负由 cosθ 决定。','真实接触角滞后和管壁不均匀会造成偏差。','边界值必须单独判断，不能并入大于或小于分支。'),
    'X3-37':L('X3-37','古木测年应把 14C 半衰期放在哪个时间尺度？',[['years','约 5730 年'],['hours','约 6 小时'],['days','约 30 天']],'years',[{selector:'#arch'}],'考古测年切换到 14C、年和约 5730 年半衰期。','核素、时间单位、曲线横轴和应用场景整体切换。','N/N0=(1/2)^(t/T) 要求 t、T 使用同一单位。','真实测年还需初始比值、校准曲线和样品处理。','应用题先选核素和尺度，再代半衰期公式。'),
    'X3-38':L('X3-38','仅凭本页相对响应能否判断实际辐射剂量安全？',[['no','不能'],['yes','响应低就一定安全'],['material','与源活度和材料无关']],'no',[{selector:'#gamma'},{selector:'#dist',value:'5.0'}],'增大距离会降低相对响应，但页面不输出剂量或安全阈值。','射线种类、距离、屏蔽材料和趋势提示共同变化。','时间、距离、屏蔽是防护原则，定量剂量还需真实源项与标定。','屏蔽衰减参数为定性示意，不可用于安全决策。','防护题先给趋势，定量结论必须引用已标定数据。'),
    'X3-39':L('X3-39','判断主导相互作用时，尺度能否脱离对象单独分类？',[['no','不能；先看对象/过程，再用尺度核对'],['yes','只拖尺度即可'],['charge','只看是否带电']],'no',[{selector:'#context',value:'beta'},{selector:'#scale',value:'-17'}],'β 衰变对象指向弱相互作用，尺度只负责检查情境是否自洽。','切换对象会改变主导作用；单独拖尺度不会改写对象结论。','四种作用的对象、范围和相对强弱必须结合判断。','同一尺度可能存在多种作用，不能把色带当成唯一分类器。','综合题先识别过程和粒子，再结合尺度与守恒规律。')
  };

  const defaults={'molecular-theory.html':'X3-01','avogadro.html':'X3-02','molecular-motion.html':'X3-03','molecular-force.html':'X3-04','internal-energy.html':'X3-05','temperature-scale.html':'X3-06','gas-state-parameters.html':'X3-07','boyle-law.html':'X3-08','charles-law.html':'X3-09','pv-graph.html':'X3-11','gas-law.html':'X3-12','first-law.html':'X3-13','second-law.html':'X3-14','energy-conservation-thermal.html':'X3-15','crystal-amorphous.html':'X3-17','surface-tension.html':'X3-18','wave-particle.html':'X3-20','atomic-structure.html':'X3-21','bohr-energy-level.html':'X3-22','atomic-spectrum.html':'X3-23','nuclear-structure.html':'X3-24','radioactive-decay.html':'X3-25','half-life.html':'X3-26','nuclear-reaction.html':'X3-27','nuclear-energy.html':'X3-28','binding-energy.html':'X3-29','nuclear-fission.html':'X3-30','nuclear-fusion.html':'X3-31','particle-physics.html':'X3-32','molecular-speed-distribution.html':'X3-33','diffusion-brownian.html':'X3-34','materials-microstructure.html':'X3-35','capillary.html':'X3-36','radioisotope-applications.html':'X3-37','radiation-protection.html':'X3-38','fundamental-interactions.html':'X3-39'};

  const motion=document.createElement('style');motion.textContent='@media (prefers-reduced-motion: reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}}';document.head.appendChild(motion);
  const media=window.matchMedia('(prefers-reduced-motion: reduce)');document.documentElement.dataset.x3Motion=media.matches?'reduce':'full';if(media.addEventListener)media.addEventListener('change',e=>{document.documentElement.dataset.x3Motion=e.matches?'reduce':'full'});
  const file=decodeURIComponent(location.pathname.split('/').pop()||''),requested=new URLSearchParams(location.search).get('lesson'),config=lessons[requested||defaults[file]],canvas=document.querySelector('canvas'),host=document.querySelector('.panel')||document.querySelector('.container')||document.querySelector('.controls')||document.querySelector('.wrap')||document.body;if(!config||!canvas||!host)return;
  pauseExistingMotion();
  const style=document.createElement('style');style.textContent=`.x3-guide{border:2px solid #7c3aed;background:#f5f3ff;color:#3b2f63;border-radius:10px;padding:10px;display:grid;gap:8px;margin:0 0 10px;min-width:0}.x3-guide h2{font-size:15px;line-height:1.45;margin:0;color:#1e1b4b}.x3-guide p{font-size:12px;line-height:1.55;margin:0}.x3-guide-options{display:grid;gap:6px}.x3-guide-options button{min-height:38px;text-align:left;padding:7px 9px;background:#fff}.x3-guide-options button[aria-pressed="true"]{border-color:#7c3aed;background:#ede9fe;color:#4c1d95;font-weight:800}.x3-guide-verify{min-height:38px;background:#7c3aed!important;border-color:#7c3aed!important;color:#fff!important;font-weight:800}.x3-guide-verify:disabled{background:#94a3b8!important;border-color:#94a3b8!important}.x3-guide-feedback{border-left:4px solid #0f766e;background:#ecfdf5;padding:8px;color:#134e4a;font-size:12px;line-height:1.58}.x3-guide-boundary,.x3-guide-transfer{border-top:1px dashed #5eead4;padding-top:7px;margin-top:6px!important}.x3-guide-transfer{border-color:#c4b5fd;color:#334155}.x3-guide-replay{min-height:36px;background:#fff!important}.x3-guide-motion{color:#475569;font-size:11px!important}.x3-guide-stage{position:relative;width:100%;min-width:0}.x3-guide-veil{position:absolute;inset:0;display:grid;place-items:center;background:rgba(245,243,255,.58);z-index:20;pointer-events:none;border-radius:10px}.x3-guide-veil span{max-width:82%;border:1px solid #a78bfa;background:rgba(255,255,255,.96);border-radius:9px;padding:9px 12px;color:#5b21b6;font-size:13px;font-weight:800;text-align:center;line-height:1.5}[data-x3-guide-answer-hidden]{visibility:hidden!important}[data-x3-guide-locked]{display:none!important}@media(max-width:760px){.x3-guide{padding:9px}.x3-guide h2{font-size:14px}}`;document.head.appendChild(style);
  const guide=document.createElement('section');guide.className='x3-guide';guide.dataset.x3Guide=config.id;guide.setAttribute('aria-label',config.id+' 引导演示');guide.innerHTML=`<h2>${esc(config.question)}</h2><p>先作预测；验证后才开放画面、读数、公式和自由探索。</p><p class="x3-guide-motion">${media.matches?'已启用减少动态：验证会直接进入静态证据状态。':'先预测，再用装置证据修正或确认。'}</p><div class="x3-guide-options" role="group" aria-label="请选择预测"></div><button class="x3-guide-verify" type="button" disabled>验证预测</button><div class="x3-guide-feedback" hidden aria-live="polite"></div><button class="x3-guide-replay" type="button" hidden>重新预测并重置</button>`;
  const task=host.querySelector('.task'),heading=host.querySelector('h1,h2');if(task)task.insertAdjacentElement('afterend',guide);else if(heading)heading.insertAdjacentElement('afterend',guide);else host.prepend(guide);
  const options=guide.querySelector('.x3-guide-options'),verify=guide.querySelector('.x3-guide-verify'),feedback=guide.querySelector('.x3-guide-feedback'),replay=guide.querySelector('.x3-guide-replay');let chosen=null;config.options.forEach(([value,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.guideChoice=value;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{chosen={value,label};options.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));verify.disabled=false});options.appendChild(b)});
  const stage=document.createElement('div');stage.className='x3-guide-stage';canvas.parentNode.insertBefore(stage,canvas);stage.appendChild(canvas);const veil=document.createElement('div');veil.className='x3-guide-veil';veil.innerHTML='<span>先完成预测，再显示清晰画面、读数和公式证据</span>';stage.appendChild(veil);canvas.style.filter='blur(5px)';canvas.style.opacity='.34';canvas.style.pointerEvents='none';canvas.dataset.guideStage='predict';document.documentElement.dataset.x3GuideStage='predict';
  const answers=[...document.querySelectorAll('.formula,.read,.readouts,.readout,.chips,#readout')].filter(n=>!guide.contains(n));answers.forEach(n=>n.setAttribute('data-x3-guide-answer-hidden',''));const controls=[...document.querySelectorAll('button,input,select,textarea')].filter(n=>!guide.contains(n)),states=new Map(controls.map(n=>[n,n.disabled]));controls.forEach(n=>{n.disabled=true;n.setAttribute('data-x3-guide-locked','')});
  verify.addEventListener('click',async()=>{if(!chosen||verify.disabled)return;verify.disabled=true;options.querySelectorAll('button').forEach(b=>{b.disabled=true});try{await run(config.actions||[])}catch(error){feedback.hidden=false;feedback.textContent='引导演示未完成：'+error.message;return}controls.forEach(n=>{n.disabled=states.get(n);n.removeAttribute('data-x3-guide-locked')});answers.forEach(n=>n.removeAttribute('data-x3-guide-answer-hidden'));veil.remove();canvas.style.filter='';canvas.style.opacity='';canvas.style.pointerEvents='';canvas.dataset.guideStage='explore';document.documentElement.dataset.x3GuideStage='explore';feedback.hidden=false;feedback.innerHTML=`<b>你的预测：</b>${esc(chosen.label)}<br><b>实际结果：</b>${esc(config.result)}<br><b>画面证据：</b>${esc(config.evidence)}<br><b>为什么：</b>${esc(config.explanation)}<p class="x3-guide-boundary"><b>模型边界：</b>${esc(config.boundary)}</p><p class="x3-guide-transfer"><b>高考迁移：</b>${esc(config.transfer)}</p>`;verify.textContent=chosen.value===config.correct?'预测已验证：开放公式与探索':'用证据修正预测：开放公式与探索';replay.hidden=false;guide.dispatchEvent(new CustomEvent('x3-guide-complete',{bubbles:true,detail:{id:config.id,choice:chosen.value}}))});replay.addEventListener('click',()=>location.reload());
  async function run(actions){for(const action of actions){const target=document.querySelector(action.selector);if(!target)throw new Error('缺少动作目标 '+action.selector);target.disabled=false;if(Object.prototype.hasOwnProperty.call(action,'value')){target.value=action.value;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}))}else target.click();await wait(action.after||80)}}
  function pauseExistingMotion(){const candidates=[...document.querySelectorAll('#play-btn,#playBtn,#play,#freeze')],running=candidates.find(b=>/暂停|冻结/.test(b.textContent||''));if(running)running.click()}
  function wait(ms){return media.matches?Promise.resolve():new Promise(resolve=>setTimeout(resolve,ms))}
  function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
