(function () {
  'use strict';

  function L(id, question, options, correct, actions, result, evidence, explanation, boundary, transfer) {
    return {id, question, options, correct, actions, result, evidence, explanation, boundary, transfer};
  }

  const lessons = {
    'X2-01':L('X2-01','小磁针放入磁场后，N 极最终指向什么方向？',[['b','该点磁场方向'],['s','S 极受力方向'],['wire','任意导线方向']],'b',[{selector:'#dir-btn'}],'N 极稳定指向该点磁场方向。','磁针、场线切线和方向标记同步改变。','磁场方向定义为小磁针 N 极静止时的指向。','探针的 |B| 只是相对强度，不是未经标定的特斯拉读数。','判断空间磁场先放置探针，再读 N 极和切线方向。'),
    'X2-02':L('X2-02','直导线与磁场垂直时，把电流增大，安培力怎样？',[['up','按比例增大'],['same','保持不变'],['zero','变为零']],'up',[{selector:'#i',value:'7'}],'电流增大，安培力随之增大。','力箭头和 F=BILsinθ 读数使用同一组参数。','垂直放置时 sinθ=1，所以 F 与 I 成正比。','只适用于匀强磁场中的直导线有效长度。','先判断夹角，再比较 B、I、L。'),
    'X2-03':L('X2-03','导线逐渐转到与 B 平行，安培力怎样？',[['down','减小到零'],['up','增大到最大'],['flip','必然反向']],'down',[{selector:'#th',value:'0'}],'导线平行 B 时安培力为零。','角度、sinθ 与力箭头同步归零。','F=BILsinθ，θ 是 I 与 B 的夹角。','载流导线方向改变时还要用左手定则判断力向。','角度题先画 I、B，再代入 sinθ。'),
    'X2-04':L('X2-04','速度反向而 q、B 不变，洛伦兹力方向怎样？',[['flip','随 v 反向'],['same','保持不变'],['work','沿 v 做功']],'flip',[{selector:'[data-sign="-1"]'}],'叉乘中任一矢量反向，磁力方向反向。','v、B、F 三个方向和 q 的符号共同决定画面箭头。','F=qv×B，大小是 |q|vBsinθ。','磁场力始终垂直瞬时速度，不改变粒子速率。','先按正电荷用右手定则，再处理负电荷反向。'),
    'X2-05':L('X2-05','B 垂直纸面向里，正电荷在纸面内怎样转弯？',[['ccw','逆时针'],['cw','顺时针'],['straight','直线']],'ccw',[{selector:'[data-sign="1"]'},{selector:'#stepBtn'}],'正电荷逆时针、负电荷顺时针。','单步后相位、速度切线和向心洛伦兹力保持叉乘一致。','磁力提供向心力，R=mv⊥/(|q|B)。','斜射还含平行 B 的匀速分量，形成螺旋。','先判电荷和 B，再画 v×B。'),
    'X2-06':L('X2-06','粒子从左边界垂直进入宽为 L 的磁场，R<L 时从哪里离开？',[['left','回到原来的左边界'],['right','穿过右边界'],['center','停在圆心']],'left',[{selector:'#rr',value:'6'},{selector:'#lr',value:'10'}],'轨迹走完右半圆并回到左边界上方。','端点、180° 扫角和“返回左边界”状态一致。','R<L 时轨道最右点仍达不到右边界。','临界 R=L 才恰好触及右边界。','有界场题先画完整圆，再与边界求交。'),
    'X2-07':L('X2-07','均匀 B 穿过平面 S，面法线转到与 B 垂直时磁通量怎样？',[['zero','变为零'],['max','最大'],['b','等于 B']],'zero',[{selector:'#tr',value:'90'}],'θ=90° 时 Φ=0。','面积投影和 Φ=BS cosθ 同步归零。','磁通量本质是有向面积分 ∫B·dS。','BS cosθ 只限均匀 B 和平面面积。','先确认 θ 是 B 与面法线夹角。'),
    'X2-08':L('X2-08','线圈中的磁通量保持不变时，会有感应电动势吗？',[['no','没有'],['yes','只要有磁场就有'],['current','只由原电流大小决定']],'no',[{selector:'#play-btn',after:260}],'只有磁通量变化才出现感应电动势。','磁通记录斜率、指针和灯泡同步。','法拉第定律响应 ΔΦ/Δt，不响应 Φ 的静态大小。','闭合回路才会进一步形成感应电流。','先查磁通是否变化，再判电动势和电流。'),
    'X2-09':L('X2-09','磁铁 N 极靠近线圈时，感应磁场怎样响应？',[['oppose','阻碍磁通量增加'],['help','帮助磁通量增加'],['none','没有方向']],'oppose',[{selector:'#n-btn'}],'感应磁场反抗原磁通量的增加。','磁铁运动、Φ 变化、线圈极性和电流计偏转共同给证据。','楞次定律中的“阻碍”针对磁通量变化。','它不意味着原磁场被完全抵消。','用“增反减同”前先判原磁通方向和变化。'),
    'X2-10':L('X2-10','相同 ΔΦ 用时更短，平均感应电动势怎样？',[['larger','更大'],['same','不变'],['zero','为零']],'larger',[{selector:'#play-angle',after:260}],'变化越快，|E| 越大。','Φ-t 曲线斜率和电压表读数同步。','平均 E=N|ΔΦ|/Δt；瞬时值对应导数。','拖拽离散采样只代表受控运动的数值近似。','读图时用斜率而不是 Φ 的高度判断 E。'),
    'X2-11':L('X2-11','无外电源的闭合导轨中，棒向右运动时磁力会怎样？',[['oppose','在被动回路中阻碍运动'],['help','总是推动运动'],['none','始终为零']],'oppose',[{selector:'#reverse-v'},{selector:'#play-btn',after:900}],'电磁作用把外力做功转成电能和热，并阻碍相对运动；棒到端点后所有运动与电磁读数归零。','速度、电动势、电流、安培力和 I²R 功率使用同一能量链。','结论限于闭合、被动、无外加电源的回路。','开路或有外电源时不能机械套“安培阻力”。','先画电源等效极性和回路电流，再判力。'),
    'X2-12':L('X2-12','开关断开后，线圈电流能否瞬间变为零？',[['no','不能；要经闭合续流回路衰减'],['yes','能立即归零'],['grow','会无限增大']],'no',[{selector:'#toggle'},{selector:'#play-btn',after:420}],'电流连续，经二极管—指示灯支路短暂续流。','断开后 source-disconnected、闭合续流路径和衰减电流同步。','自感电动势阻碍电流变化，而不是维持断开的原电源回路。','没有闭合续流路径时要用开关电弧、寄生参数等更复杂模型。','自感断电题必须先画断开后的实际回路。'),
    'X2-13':L('X2-13','原线圈电流恒定时，副线圈是否持续产生感应电动势？',[['no','不会，稳定 B 使 dΦ₂/dt=0'],['yes','会持续产生'],['wire','只有电连接才有']],'no',[{selector:'#pulseBtn'}],'只有 I₁ 改变阶段，副线圈才有 E₂。','I₁、B、Φ₂、E₂ 按因果链依次变化。','互感传递的是变化磁场，不是导线中的直接电流。','耦合系数受距离、铁芯和几何影响。','从 dI₁/dt 开始追踪到 E₂。'),
    'X2-14':L('X2-14','线圈匀速转动且 B 均匀时，感应电动势为何是正弦？',[['projection','磁通量投影随角度作余弦变化'],['all','任意转动都严格正弦'],['field','因为 B 自己变成正弦']],'projection',[{selector:'#w',value:'3'}],'理想条件下 Φ 为余弦，e 为其时间导数的正弦。','线圈角度、Φ-t 与 e-t 相差四分之一周期。','还要求线圈面积和角速度恒定、B 均匀。','实际发电机波形可能含谐波和损耗。','写正弦式前先声明计时零点和理想条件。'),
    'X2-15':L('X2-15','完整正弦周期的有符号平均电压是多少？',[['zero','0'],['half','2Um/π'],['rms','Um/√2']],'zero',[{selector:'#umr',value:'400'}],'完整周期有符号平均为 0；2Um/π 是半周期平均大小。','瞬时值、有效值、半周期平均和全周期平均分别标注。','有效值由热效应定义，与平均值不是同一量。','q=N|ΔΦ|/R总只针对给定磁通变化区间和方向约定。','先识别题目问瞬时、峰值、有效值还是区间平均。'),
    'X2-16':L('X2-16','理想变压器原线圈接稳定直流，副线圈会持续有电压吗？',[['no','不会'],['yes','会按匝数比持续变压'],['heat','只改变频率']],'no',[{selector:'#n2',value:'800'}],'稳定直流建立后磁通不再变化，副边电压回到零。','匝数变化只改变交流/变化磁通下的比例读数。','变压器需要变化磁通；交流或脉冲直流可以耦合。','理想匝数比忽略漏磁、铜耗、铁耗和负载压降。','先分稳态直流与时变输入，再使用匝数比。'),
    'X2-17':L('X2-17','固定输送功率和线路电阻，提高电压为何能降损？',[['current','电流减小，I²r 按平方下降'],['resistance','线路电阻自动变零'],['power','用户功率必然大于输入']],'current',[{selector:'#ur',value:'20'}],'有效区内提高 U 会降低 I 和线路损耗。','I、P损、ΔU、用户功率和效率共同满足能量边界。','参数若导致 P损≥P 或 ΔU≥U，页面拒绝给出伪读数。','模型忽略无功、功率因数和变压器损耗。','先检查模型有效性，再比较 U 与损耗。'),
    'X2-18':L('X2-18','热敏电阻受热时阻值变化是否只有一种方向？',[['types','不是；NTC 降、PTC 升'],['down','都下降'],['up','都上升']],'types',[{selector:'[data-mode="temp"]'}],'NTC 与 PTC 对温度的响应方向相反。','模式、输入量、传感器电阻和阈值状态同步。','传感器把非电学量转换为可处理的电信号。','还需分压、标定、量程和处理电路。','看到热敏元件先确认 NTC/PTC 类型。'),
    'X2-19':L('X2-19','电磁驱动中金属盘为何必须落后于旋转磁场？',[['slip','保持转差才能持续改变磁通并产生转矩'],['same','完全同步时转矩最大'],['translate','磁场只做平移']],'slip',[{selector:'[data-mode="drive"]'}],'旋转场领先金属盘，转差产生涡流和同向驱动转矩。','旋转场角、盘角和转差率独立记录。','若完全同步，盘中磁通不再相对变化，驱动涡流趋零。','强弱读数是定性相对量，不是未标定百分比。','区分阻尼的反向力与驱动的同向转矩。'),
    'X2-20':L('X2-20','理想 LC 振荡中，电容电荷最大时线圈电流怎样？',[['zero','为零'],['max','最大'],['same','与电荷同相最大']],'zero',[{selector:'#l',value:'5'}],'电场能最大时电流为零，随后向磁场能转化。','q、I、电场能、磁场能用同一相位。','理想 LC 中总能量守恒，q 与 I 相差四分之一周期。','真实电阻会导致阻尼，需外加能量才能维持。','用能量互换快速判断极值时刻。'),
    'X2-21':L('X2-21','真空平面电磁波中 E 与 B 的相位关系怎样？',[['same','同相'],['opposite','反相'],['quarter','相差四分之一周期']],'same',[{selector:'#x',value:'65'}],'归一化的 E/E₀ 与 B/B₀ 同相。','两条曲线同峰同谷，E×B 指向传播方向。','真空中幅值还满足 E₀=cB₀。','不能把不同量纲的 E、B 直接写成数值相等。','先判相位与方向，再处理幅值单位。'),
    'X2-22':L('X2-22','接收频率已经调准，但距离很远导致信号弱，能否说“频率失配”？',[['no','不能；调谐与传播衰减要分开'],['yes','弱就等于失配'],['delay','只看传播延迟']],'no',[{selector:'#tune',value:'100'},{selector:'#dist',value:'100'}],'页面显示“已调谐，但距离导致传播衰减”。','频差判据和距离衰减因子分别计算。','选频决定是否匹配，传播决定到达强度。','真实传播还含方向性、吸收、遮挡和噪声。','通信题把调制、传播、调谐、解调逐段诊断。'),
    'X2-23':L('X2-23','电磁波频率越高，是否就能只凭波段名称断言一定危险？',[['context','不能，还要看强度、剂量和暴露条件'],['yes','一定更危险'],['none','所有波都无风险']],'context',[{selector:'#logf',value:'18'}],'频率决定光子能量趋势，但风险还取决于强度、剂量和暴露。','波段、频率、波长、单光子能量与防护提示联动。','波段分界是近似约定，不是绝对断层。','应用和安全结论必须结合具体源与剂量。','先定波段和能量，再读题目给定的暴露条件。'),
    'X2-24':L('X2-24','发电机外接负载开路时，即使有感应电动势，功率输出怎样？',[['zero','I=0，电功率输出为 0'],['max','达到最大'],['negative','变成负功率']],'zero',[{selector:'#load',value:'0'}],'开路时 I=0，机械输入和电功率输出都为 0。','电动势读数可非零，但能量账各项严格守恒。','功率传递需要闭合回路和电流。','本页是简化等效电阻模型，未模拟铁耗和摩擦基线。','能量题逐项写输入、有效输出和损耗并核对单位。')
  };

  const defaults={'magnetic-field.html':'X2-01','ampere-force.html':'X2-02','lorentz-force.html':'X2-04','magnetic-circle.html':'X2-05','magnetic-critical.html':'X2-06','magnetic-flux.html':'X2-07','lenz-law.html':'X2-08','faraday-law.html':'X2-10','rail-rod.html':'X2-11','self-induction.html':'X2-12','mutual-induction.html':'X2-13','ac-generation.html':'X2-14','ac-values.html':'X2-15','transformer.html':'X2-16','power-transmission.html':'X2-17','sensor.html':'X2-18','eddy-current.html':'X2-19','lc-oscillation.html':'X2-20','maxwell-em-theory.html':'X2-21','em-wave-transmission.html':'X2-22','em-spectrum.html':'X2-23','generator-motor.html':'X2-24'};

  const motion=document.createElement('style');motion.textContent='@media (prefers-reduced-motion: reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}}';document.head.appendChild(motion);
  const media=window.matchMedia('(prefers-reduced-motion: reduce)');document.documentElement.dataset.x2Motion=media.matches?'reduce':'full';if(media.addEventListener)media.addEventListener('change',e=>{document.documentElement.dataset.x2Motion=e.matches?'reduce':'full'});
  const file=decodeURIComponent(location.pathname.split('/').pop()||''),requested=new URLSearchParams(location.search).get('lesson'),config=lessons[requested||defaults[file]],canvas=document.querySelector('canvas'),host=document.querySelector('.panel')||document.querySelector('.container')||document.querySelector('.wrap')||document.body;if(!config||!canvas||!host)return;
  pauseExistingMotion();
  const style=document.createElement('style');style.textContent=`.x2-guide{border:2px solid #2563eb;background:#eff6ff;color:#1e3a5f;border-radius:10px;padding:10px;display:grid;gap:8px;margin:0 0 10px;min-width:0}.x2-guide h2{font-size:15px;line-height:1.45;margin:0;color:#0f172a}.x2-guide p{font-size:12px;line-height:1.55;margin:0}.x2-guide-options{display:grid;gap:6px}.x2-guide-options button{min-height:38px;text-align:left;padding:7px 9px;background:#fff}.x2-guide-options button[aria-pressed="true"]{border-color:#2563eb;background:#dbeafe;color:#1e3a8a;font-weight:800}.x2-guide-verify{min-height:38px;background:#2563eb!important;border-color:#2563eb!important;color:#fff!important;font-weight:800}.x2-guide-verify:disabled{background:#94a3b8!important;border-color:#94a3b8!important}.x2-guide-feedback{border-left:4px solid #0f766e;background:#ecfdf5;padding:8px;color:#134e4a;font-size:12px;line-height:1.58}.x2-guide-boundary,.x2-guide-transfer{border-top:1px dashed #5eead4;padding-top:7px;margin-top:6px!important}.x2-guide-transfer{border-color:#93c5fd;color:#334155}.x2-guide-replay{min-height:36px;background:#fff!important}.x2-guide-motion{color:#475569;font-size:11px!important}.x2-guide-stage{position:relative;width:100%;min-width:0}.x2-guide-veil{position:absolute;inset:0;display:grid;place-items:center;background:rgba(239,246,255,.54);z-index:20;pointer-events:none;border-radius:10px}.x2-guide-veil span{max-width:82%;border:1px solid #60a5fa;background:rgba(255,255,255,.96);border-radius:9px;padding:9px 12px;color:#1e3a8a;font-size:13px;font-weight:800;text-align:center;line-height:1.5}[data-x2-guide-answer-hidden]{visibility:hidden!important}[data-x2-guide-locked]{display:none!important}@media(max-width:760px){.x2-guide{padding:9px}.x2-guide h2{font-size:14px}}`;document.head.appendChild(style);
  const guide=document.createElement('section');guide.className='x2-guide';guide.dataset.x2Guide=config.id;guide.setAttribute('aria-label',config.id+' 引导演示');guide.innerHTML=`<h2>${esc(config.question)}</h2><p>先作预测；验证后才开放画面、读数、公式和自由探索。</p><p class="x2-guide-motion">${media.matches?'已启用减少动态：验证会直接进入静态证据状态。':'先预测，再用装置证据修正或确认。'}</p><div class="x2-guide-options" role="group" aria-label="请选择预测"></div><button class="x2-guide-verify" type="button" disabled>验证预测</button><div class="x2-guide-feedback" hidden aria-live="polite"></div><button class="x2-guide-replay" type="button" hidden>重新预测并重置</button>`;
  const task=host.querySelector('.task'),heading=host.querySelector('h1,h2');if(task)task.insertAdjacentElement('afterend',guide);else if(heading)heading.insertAdjacentElement('afterend',guide);else host.prepend(guide);
  const options=guide.querySelector('.x2-guide-options'),verify=guide.querySelector('.x2-guide-verify'),feedback=guide.querySelector('.x2-guide-feedback'),replay=guide.querySelector('.x2-guide-replay');let chosen=null;config.options.forEach(([value,label])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.guideChoice=value;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{chosen={value,label};options.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));verify.disabled=false});options.appendChild(b)});
  const stage=document.createElement('div');stage.className='x2-guide-stage';canvas.parentNode.insertBefore(stage,canvas);stage.appendChild(canvas);const veil=document.createElement('div');veil.className='x2-guide-veil';veil.innerHTML='<span>先完成预测，再显示清晰画面、读数和公式证据</span>';stage.appendChild(veil);canvas.style.filter='blur(5px)';canvas.style.opacity='.34';canvas.style.pointerEvents='none';canvas.dataset.guideStage='predict';document.documentElement.dataset.x2GuideStage='predict';
  const answers=[...document.querySelectorAll('.formula,.read,.readouts,.readout,.chips,#readout')].filter(n=>!guide.contains(n));answers.forEach(n=>n.setAttribute('data-x2-guide-answer-hidden',''));const controls=[...document.querySelectorAll('button,input,select,textarea')].filter(n=>!guide.contains(n)),states=new Map(controls.map(n=>[n,n.disabled]));controls.forEach(n=>{n.disabled=true;n.setAttribute('data-x2-guide-locked','')});
  verify.addEventListener('click',async()=>{if(!chosen||verify.disabled)return;verify.disabled=true;options.querySelectorAll('button').forEach(b=>{b.disabled=true});try{await run(config.actions||[])}catch(error){feedback.hidden=false;feedback.textContent='引导演示未完成：'+error.message;return}controls.forEach(n=>{n.disabled=states.get(n);n.removeAttribute('data-x2-guide-locked')});answers.forEach(n=>n.removeAttribute('data-x2-guide-answer-hidden'));veil.remove();canvas.style.filter='';canvas.style.opacity='';canvas.style.pointerEvents='';canvas.dataset.guideStage='explore';document.documentElement.dataset.x2GuideStage='explore';feedback.hidden=false;feedback.innerHTML=`<b>你的预测：</b>${esc(chosen.label)}<br><b>实际结果：</b>${esc(config.result)}<br><b>画面证据：</b>${esc(config.evidence)}<br><b>为什么：</b>${esc(config.explanation)}<p class="x2-guide-boundary"><b>模型边界：</b>${esc(config.boundary)}</p><p class="x2-guide-transfer"><b>高考迁移：</b>${esc(config.transfer)}</p>`;verify.textContent=chosen.value===config.correct?'预测已验证：开放公式与探索':'用证据修正预测：开放公式与探索';replay.hidden=false;guide.dispatchEvent(new CustomEvent('x2-guide-complete',{bubbles:true,detail:{id:config.id,choice:chosen.value}}))});replay.addEventListener('click',()=>location.reload());
  async function run(actions){for(const action of actions){const target=document.querySelector(action.selector);if(!target)throw new Error('缺少动作目标 '+action.selector);target.disabled=false;if(Object.prototype.hasOwnProperty.call(action,'value')){target.value=action.value;target.dispatchEvent(new Event('input',{bubbles:true}));target.dispatchEvent(new Event('change',{bubbles:true}))}else target.click();await wait(action.after||80)}}
  function pauseExistingMotion(){const candidates=[...document.querySelectorAll('#play-btn,#playBtn,#play,#freeze')],running=candidates.find(b=>/暂停|冻结/.test(b.textContent||''));if(running)running.click()}
  function wait(ms){return media.matches?Promise.resolve():new Promise(resolve=>setTimeout(resolve,ms))}
  function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
